### ISSUE TITLE
Data set

### ISSUE THREAD

**Issue by vinayakumarr** [endgameinc/youarespecial#1]
Where we can find the data set repository for benign and malicious applications

**Comment by drhyrum** [comment]
Sorry, we're unable to provide the raw binaries.  However, for the first example:
https://github.com/endgameinc/youarespecial/blob/master/BSidesLV%20--%20your%20model%20isn't%20that%20special%20--%20(1)%20MLP.ipynb

With not much work, you could use features extracted from the ember dataset:
https://github.com/endgameinc/ember
