### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by srihitha97** [endgameinc/youarespecial#2]
can i use the Ember data set directly as input for the malicious and benign data, if so how can I do it, as in which path to give and where?

**Comment by drhyrum** [comment]
Sorry, no.  The raw binaries are unavailable.

With a little work, you might get the first example working
https://github.com/endgameinc/youarespecial/blob/master/BSidesLV%20--%20your%20model%20isn't%20that%20special%20--%20(1)%20MLP.ipynb

with data/code provided in the EMBER dataset:
https://github.com/endgameinc/ember
