### ISSUE TITLE
can you share data please: 100K malicious and benign samples.

### ISSUE THREAD

**Issue by Sandy4321** [endgameinc/youarespecial#4]
great code thanks
it become famous for example mentioned in the book
Machine Learning and Security Protecting Systems with Data and Algorithms O’Reilly Media 2018
Only it would be very kind of you to share data "100K malicious and benign samples", as you mention , to reproduce your results 

So it will be possible to use this code
def fetch_samples():
    ''' fetches malicious and benign samples form disk
    For simplicity, it assumes that samples are named by their sha256 hash, and 
    are stored in benign/ and malicious/ subdirectories.
    Returns a dict "labels", where 
      labels[sha256] = 0 for a benign sha256, or 
      labels[sha256] = 1 for a malicious sha256'''
    labels = [(sha256, 0) for sha256 in os.listdir('benign')]
    labels += [(sha256, 1) for sha256 in os.listdir('malicious')]
    labels = dict(labels)
    return labels

**Comment by drhyrum** [comment]
Unfortunately, copyright law prevents sharing the benign samples needed to reproduce the end-to-end deep learning results.  However, to reproduce the feature-based models, please refer to https://github.com/EndgameInc/ember.

**Comment by Sandy4321** [comment]
thanks, do you know another  sources of this kind of data?
